#!/usr/bin/env python3
"""
ArizoRAE — Scraper template for {{ user_name }}.
Generated by agent-worker (claude-sonnet-4-6). Do not edit header.
Contract: class Scraper with run() -> list[dict]. Print JSON array on last stdout line.
"""

import argparse
import json
import sys
from playwright.sync_api import sync_playwright

# ─── Configuration (personnalisée par Claude lors de la génération) ────────────

JOBBOARDS = [
    # Exemple : {"name": "ICTJob.be", "url": "https://www.ictjob.be/...", "type": "ictjob"}
    {% for jb in jobboards %}
    {"name": "{{ jb.name }}", "url": "{{ jb.url }}", "type": "{{ jb.type }}"},
    {% endfor %}
]

HIGH_MATCH: list[str] = {{ high_match | tojson }}
LOW_MATCH: list[str] = {{ low_match | tojson }}
EXCLUDE: list[str] = {{ exclude | tojson }}
MIN_SCORE: int = {{ min_score | default(1) }}

# ─── Scoring ──────────────────────────────────────────────────────────────────

def score_offer(title: str, company: str = "", location: str = "", description: str = "") -> tuple[int, list[str]]:
    text = f"{title} {company} {location} {description}".lower()
    reasons: list[str] = []
    if any(k in text for k in EXCLUDE):
        return -1, ["excluded"]
    score = 0
    for k in HIGH_MATCH:
        if k in text:
            score += 2
            reasons.append(f"+2 {k}")
    for k in LOW_MATCH:
        if k in text:
            score += 1
            reasons.append(f"+1 {k}")
    return score, reasons


# ─── Fetchers (à implémenter par jobboard) ────────────────────────────────────

class Scraper:
    def __init__(self) -> None:
        self.results: list[dict] = []

    def run(self) -> list[dict]:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
                ),
                locale="fr-BE",
            )
            for jb in JOBBOARDS:
                try:
                    offers = self._fetch(context, jb)
                    self.results.extend(offers)
                except Exception as e:
                    print(f"[WARN] {jb['name']}: {e}", file=sys.stderr)
            browser.close()

        filtered = [o for o in self.results if o.get("score", 0) >= MIN_SCORE]
        filtered.sort(key=lambda x: x["score"], reverse=True)
        return filtered

    def _fetch(self, context, jb: dict) -> list[dict]:
        # Default implementation: override per-jobboard below
        page = context.new_page()
        page.goto(jb["url"], wait_until="domcontentloaded", timeout=30_000)

        offers: list[dict] = []
        # TODO: Claude remplace ce bloc par le parseur spécifique au jobboard
        # Chaque offer dict doit contenir :
        # external_id, source, title, company, location, url, score, score_reasons
        page.close()
        return offers


# ─── Entry point ──────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--limit", type=int, default=0)
    args = parser.parse_args()

    scraper = Scraper()
    results = scraper.run()

    if args.demo and args.limit:
        results = results[: args.limit]

    # Last line must be the JSON array (runner.py picks it up)
    print(json.dumps(results, ensure_ascii=False))


if __name__ == "__main__":
    main()
